name: PhD-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - fenics
  - matplotlib
  - pandas
  - scipy
  - sympy
  - numpy=1.24
  - mpi4py<4
  - pip>=20.1
  - gmsh
  - meshio
  - h5py
  - pip:
      - git+https://github.com/festim-dev/FESTIM@79d8fa7
      - h-transport-materials
      - pypalettes
      - pyenergydiagrams
      - mpmath
      - matplotx