name: Build LaTeX document and release PDF
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Set up LaTeX
        run: |
          sudo apt -y install make texlive-full ttf-mscorefonts-installer
          sudo fc-cache -fv

      - name: Compile dissertation
        run: |
          cd ./Thesis
          make synopsis

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: synopsis.pdf
          path: ./Thesis/synopsis.pdf

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          path: github_artifacts

      - name: move
        run: mkdir -p github_deploy && mv github_artifacts/*/* github_deploy

      - name: deploy on orphan branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: build
          force_orphan: true