name: Build LaTeX document and release PDF
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
      - uses: actions/checkout@v4

      - name: Set up LaTeX
        run: |
          sudo apt -y install make texlive-full ttf-mscorefonts-installer
          sudo fc-cache -fv

      - name: Compile dissertation
        run: |
          cd ./Thesis
          make dissertation

      - name: Upload Release Asset
      - uses: actions/upload-artifact@v4
        with:
          name: compiledPDF
          path: ./Thesis/dissertation.pdf